### ISSUE TITLE
[UX] Text doesn't wrap in WYSIWYG Source view

### ISSUE THREAD

**Issue by jackaponte** [backdrop/backdrop-issues#1848]
In Backdrop 1.3.5, text doesn't wrap in the Source view accessible via the WYSIWYG, making it hard for users to work with the source code. This is apparently due to [a bug in CKEditor](https://drupal.stackexchange.com/a/151880). The fix suggested in that StackExchange answer works for me in Backdrop; I edited `core/misc/ckeditor/skins/moono/editor_gecko.css` to change the `white-space` property of the `cke_source` selector to `pre-wrap`.

I'd submit a pull request for that code change; however, I'm not sure that essentially patching CKEditor out of band in Backdrop core is the best approach. [This CKEditor ticket](http://dev.ckeditor.com/ticket/13031) and [this CKEditor git commit](https://github.com/ckeditor/ckeditor-dev/commit/26716b3), if I'm reading it correctly, indicates that this is fixed in CKEditor 4.4.8, and 4.4.7 is included in Backdrop; is the answer therefore to [wait for 4.5.x in Backdrop core](https://github.com/backdrop/backdrop-issues/issues/1560) or use https://github.com/backdrop-contrib/ckeditor_addon?

**Comment by BWPanda** [comment]
Is this still an issue, or has it already been fixed upstream?

**Comment by klonos** [comment]
I have run https://raw.githubusercontent.com/backdrop/backdrop/1.x/core/misc/ckeditor/skins/moono-lisa/editor_gecko.css through an online CSS beautifier, and see this:

```css
textarea.cke_source {
  font-family: 'Courier New', Monospace;
  font-size: small;
  background-color: #fff;
  white-space: pre-wrap;
  border: 0;
  padding: 0;
  margin: 0;
  display: block
}
```

I am calling this fixed 😄
