### ISSUE TITLE
unset fields descriptions at user account

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2146]
Hi

Please, can not unset fields descriptions at the user edit form `/user/1/edit`

I use this code:
`$form['account']['#description'] = '';`

**Comment by klonos** [comment]
Hello @bd0bd are you using a custom module to achieve this? I would suggest hiding those descriptions using css instead of php. What I would do is create a sub-theme of Seven and set that as the default admin theme. Then you can add your custom css to achieve what you want. Something like this would work:

```css
#user-profile-form #edit-account div.description {
  display: none;
}
```

This will hide all field descriptions in that form besides the description for the user profile picture. If you need that hidden too, then try this instead:

```css
#user-profile-form #edit-account div.description,
#user-profile-form #edit-picture div.description {
  display: none;
}
```
