### ISSUE TITLE
Width of items in dropdown menu change on hover

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3038]
I have a custom theme and am yet to style the main menu (so it's currently using the default CSS). I've noticed that parent menu items (with a dropdown) are shorter than other menu items. When you hover over a parent, the width increases to what (I believe) it should be in the first place. Here's a video to show what's happening:

![peek 2018-04-19 16-12](https://user-images.githubusercontent.com/2385329/38993729-1258b7c2-43ed-11e8-9333-4e3ac4ba88bc.gif)

This appears to come from the following CSS:

core/modules/system/css/menu-dropdown.theme.css:96
```css
.menu-dropdown li.has-children > a {
  padding-right: 24px;
}
```

core/modules/system/css/menu-dropdown.theme.css:13
```css
.js .menu-dropdown a,
.js .menu-dropdown a:hover,
.js .menu-dropdown a:focus,
.js .menu-dropdown a:active {
  padding-right: 58px;
  font-weight: normal;
  line-height: 17px;
  text-decoration: none;
}
```

I'm wondering why this is?
