### ISSUE TITLE
Floated images with and without captions display differently

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3043]
In https://github.com/backdrop/backdrop-issues/issues/379 we added the ability to float images in an editor. I've just noticed that, depending on whether or not an image has a caption, images display differently.

Here's the markup and CSS for a floated image *without* a caption:

```html
<p>
  <img alt="" data-file-id="[FID]" src="[URL]" class="align-right">
</p>
```

```css
img.align-right {
  margin-left: 2em;
  margin-bottom: 1em;
}

.align-right {
  float: right;
}
```

And here's the markup and CSS for a floated image *with* a caption:

```html
<figure class="caption caption-img align-right">
  <img alt="" data-file-id="[FID]" src="[URL]">
  <figcaption>Caption goes here...</figcaption>
</figure>
```

```css
.caption {
  display: table;
  max-width: 100%;
  margin: 0 12px 10px;
}

.align-right {
  float: right;
}
```

The main issue here, IMO, is the difference with the margins. Can/should we change them to be the same both ways?
