### ISSUE TITLE
[UX] Fix RTL in the Manage blocks page

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3637]
url page admin/structure/layouts/manage/home
before
![fix rtl layout admin](https://user-images.githubusercontent.com/45591694/55275671-6ddccf80-52fa-11e9-9427-7b200eb06a9b.jpg)

after
![fix rtl layout admin-1](https://user-images.githubusercontent.com/45591694/55275676-77663780-52fa-11e9-8390-91855c84f086.jpg)

edit core\modules\layout\css\layout.admin.css
```css
[dir="rtl"] .layout-editor-region-title .label {
  padding-right: 4px;
  padding-left: 12px;
```
to
```css
[dir="rtl"] .layout-editor-region-title .label {
  float:right;	
  padding-right: 4px;
  padding-left: 12px;
}
```

after
```css
.layout-editor-region-title .dropbutton-wrapper {
  float: left;
  width: 140px;
  margin: 4px 0 10px
}
```
add
```css
[dir="rtl"] .layout-editor-region-title .dropbutton-wrapper {
  float: right;
}
```

and edit file core\misc\dropbutton.css
```css
[dir="rtl"].js .dropbutton li,
[dir="rtl"].js .dropbutton a {
  text-align: left;
}
```
to 
```css
[dir="rtl"].js .dropbutton li,
[dir="rtl"].js .dropbutton a {
  text-align: right;
}
```

---
PR: https://github.com/backdrop/backdrop/pull/2561
