### ISSUE TITLE
[UX] Fix RTL text within dropbuttons

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3642]
This was reported in #3637, but it is not limited to only the dropbuttons within the "Manage blocks" page (in fact it works as expected in that page). The problem exists in other pages, like `admin/structure/views` for example:

![fix rtl layout admin-2](https://user-images.githubusercontent.com/45591694/55294443-d4e9a980-540a-11e9-9c08-6ffe0993abf2.jpg)

@shabibalm:

> hey @klonos its working fine just in the page `admin/structure/layouts/manage/home ` but dropbutton text aligned right need edit other pages look 
> 
> `admin/structure/types`
> ![admin-structure-types](https://user-images.githubusercontent.com/45591694/55312055-35a9ce00-546d-11e9-8764-035b75cf3d18.jpg)
> 
> `admin/structure/block`
> ![admin-structure-block](https://user-images.githubusercontent.com/45591694/55312082-42c6bd00-546d-11e9-95ae-6d18cf295965.jpg)
> 
> fix all pages RTL dropbutton text aligned right 
> 
> edit file `core\misc\dropbutton.css`
> 
> ```css
> [dir="rtl"].js .dropbutton li,
> [dir="rtl"].js .dropbutton a {
>   text-align: left;
> }
> ```
> 
> to
> 
> ```css
> [dir="rtl"].js .dropbutton li,
> [dir="rtl"].js .dropbutton a {
>   text-align: right;
> }
> ```

---
PR: ...

**Comment by klonos** [comment]
...hmm, seems that we can fix this by removing the entire `[dir="rtl"]` block of css, since there is a LTR block just before it, which specifies `text-align: right`:

```css
.js .dropbutton li,
.js .dropbutton a {
  display: block;
  text-align: right; /* LTR */
}
[dir="rtl"].js .dropbutton li,
[dir="rtl"].js .dropbutton a {
  text-align: left;
}
```

We'll need to look into this a bit further, since this change will affect all dropbuttons used in core.
