### ISSUE TITLE
Support multisites in `install.sh`

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4151]
**Description of the need**
If you want to install Backdrop from the command line using the core `install.sh` script, you can only do a regular install. You can't do a multisite install.

Setting up a Backdrop installation for multisite, and then accessing the GUI installer works fine - the `/sites/[SITE]/settings.php` is updated with the DB info, config directories, etc.
But setting up the same Backdrop multisite installation, and then accessing the command line installer, doesn't work - the core `/settings.php` is updated with the DB info, config directories, etc., not the site-specific one.

**Proposed solution**
The command line installer should work the same as the GUI one; however it is that the GUI one knows to check for site-specific directories, the command line one should do the same.

**Alternatives that have been considered**
For now multisites have to be setup via the GUI, but that's not always possible (e.g. setting up a non-interactive test environment).

**Additional information**
To test, here's a Lando file for setting up the multisite environment:

```yaml
name: multisite
recipe: backdrop
config:
  webroot: www
services:
  appserver:
    build:
      - git clone https://github.com/backdrop/backdrop.git /app/www
      - mkdir /app/www/sites/multisite && cp /app/www/settings.php /app/www/sites/multisite/
```
I couldn't do this as part of the Lando setup, so one you run `lando start` you have to manually add this to the `/sites/sites.php` file:
`$sites['multisite.lndo.site'] = 'multisite';`

---

PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2946
