### ISSUE TITLE
Basis: Update box-sizing method

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4208]
Basis has the following in its `base.css` file:

```css
* {
  box-sizing: border-box;
}
```

According to [CSS-Tricks](https://css-tricks.com/box-sizing/#article-header-id-3), this is an old method of setting `box-sizing`. There's an updated method that may be better:

```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

This newer method not only helps with pseudo elements, but also allows easier overriding of box-sizing if need be (see the linked article for more details).

Can/should we update Basis to use the newer method?

- - - - - - - - 
Here's a PR: backdrop/backdrop#2991
