### ISSUE TITLE
[DX] Clean up CSS that was previously rendering the "Add role" button next to the respective text field

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4506]
For /admin/config/people/roles page

<img width="1244" alt="Screen Shot 2020-09-23 at 3 31 00 PM" src="https://user-images.githubusercontent.com/397895/94076391-d1da3a00-fdb1-11ea-9445-2a109b997250.png">

This entire section of CSS is trying to put the "Add role" button next to the respective text field:

```css
/**
 * Override default textfield float to put the "Add role" button next to
 * the input textfield.
 */
#user-admin-roles td.edit-name {
  clear: both;
}
#user-admin-roles .form-item-name {
  float: left; /* LTR */
  margin-right: 1em; /* LTR */
}
[dir="rtl"] #user-admin-roles .form-item-name {
  float: right;
  margin-left: 1em;
  margin-right: 0;
}
```
(https://github.com/backdrop/backdrop/blob/1.x/core/modules/user/css/user.css#L23)

In D7, both the text field and the button were rendered in the same table cell, with `colspan="4"`, but we've moved the button in the "Operations" column in Backdrop. Do we prefer it that way (visually, it makes sense to have it horizontally aligned with the rest of the operations drop-buttons), or should we move it back next to the text field (less distance for the mouse to travel)?

This was split off of #4504...
