### ISSUE TITLE
Duplicate .drop-lounging CSS in skin.css

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#4625]
The CSS that places Drop in the Powered-By footer block is in the `footer.css` file.  However, part of the CSS is also duplicated in `skin.css`.

This bit is in `skin.css`.  It's also in `component/footer.css`, minus the comments.
```css
.drop-lounging {
  /* To make Drop larger/smaller, adjust the width below. */
  width: 7em;
}

.drop-lounging:before {
  /* Uncomment below to remove Drop, or remove markup from block--system--powered-by.tpl.php */
  /* display: none; */
  background-image: url("../images/drop-lounging.png");
}
```

Backdrop 1.17.0
