### ISSUE TITLE
Removed duplicate selectors in Seven's Vertical Tabs CSS file

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4834]
The core Seven theme has unnecessary duplicate selectors in its [Vertical Tabs CSS file](https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/css/vertical-tabs.css#L147-L152):

```css
.vertical-tab-link:focus,
.vertical-tab-link:active,
.vertical-tab-link:hover,
.vertical-tab-link:focus,
.vertical-tab-link:active,
.vertical-tab-link:hover {
  text-decoration: none;
  background: #d5d5d5;
}
```

I think the duplicates can be safely removed.
