### ISSUE TITLE
Remove duplicate CSS in system.admin.css

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4843]
There is duplicate CSS in `system.admin.css` that should be removed:

```css

.system-status-report .report-error .status-summary {
  color: #EC351C;
}
@media all and (min-width: 721px) {
  .system-status-report .status-summary-mobile {
    display: none;
  }
}
@media all and (min-width: 768px) {
  .system-status-report td {
    padding: 10px 20px;
  }
  .system-status-report .status-title {
    white-space: nowrap;
  }
}
.system-status-report .report-error .status-summary {
  color: #EC351C;
}
```

Note the first and last selector above.
