### ISSUE TITLE
Fix fragment identifier targets from being covered

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5862]
## Description of the bug

With the _Administration Bar_ module disabled clicking on such links you can see at least the part of the relevant content:

![Screenshot 2022-11-15 at 3 39 44 PM](https://user-images.githubusercontent.com/56604405/202032937-299995e9-7cc4-4fdf-aa4c-b2cda7d14439.png)

However, Backdrop comes with _Administration Bar_ module enabled and it remains enabled on most of the websites, so clicking the same link takes you too far and you are not able to see relevant content at all. You would have to scroll little bit up to see the right content:

![Screenshot 2022-11-15 at 4 01 46 PM](https://user-images.githubusercontent.com/56604405/202034411-30c1fee7-e68e-4050-be5c-9b82a9084cbc.png)

## Expected behavior

Ideally, you should be able to see not only the part of the relevant content, but all of it including the title like so:

![Screenshot 2022-11-15 at 3 56 25 PM](https://user-images.githubusercontent.com/56604405/202033738-31f09863-8ea7-4e42-8191-3343f2dc113b.png)

I see from various publications like, for example, https://css-tricks.com/hash-tag-links-padding/ it's a common browser issue. However, Backdrop's _Administration Bar_ module is making it even worse. I am not sure what's the ideal solution here, so suggestions are welcome.

**Comment by olafgrabienski** [comment]
Good point! Inspired by the CSS tricks article, I've added the following styles via *CSS Injector* on top of the *Seven* theme of a test site. What do you think of it?

```
#permissions td.module:target {
  padding-top:51px;
  background: #ffe082;
}
.admin-bar #permissions td.module:target {
  padding-top:84px;
}
```

The `background` isn't necessary but helps with testing (and may even be a general enhancement).

**Comment by olafgrabienski** [comment]
Screenshot based on the CSS fix:

<img width="612" alt="backdrop-permissions-css-fix" src="https://user-images.githubusercontent.com/14188307/202193639-c6c75713-6af6-4b19-bfc3-52212276b549.png">

**Comment by indigoxela** [comment]
There's an alternate solution for that - [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top):

```
.admin-bar :target {
  scroll-margin-top: 34px;
}
```

**Comment by alanmels** [comment]
I believe the solution should not be specifically for the Permissions page as the problem persists anywhere, take for example https://sandbox.ddev.site/admin/modules#module-comment. Not sure what's the ideal solution, but I really like @olafgrabienski's idea of making the target section outstanding by changing the background color. 

I'm just afraid there would be too many css rules if we are to specify each possible target, so ideally some kind of universal solution for any link with anchor be found, maybe including a new jquery condition rule.

**Comment by olafgrabienski** [comment]
> I believe the solution should not be specifically for the Permissions page ...

Agreed, a more general approach is preferable, but wouldn't work for the background. (The Permissions page seems however more important to me, as its anchors are linked from the Modules page's dropbuttons. Also, the background could be a follow-up.)

@indigoxela, unfortunately your (more general) approach with `scroll-margin-top` doesn't work for me, it doesn't change the position of the target element when I jump to it using an anchor link.

**Comment by NormPlum** [comment]
Here is some CSS that works for me to set a margin above a targeted element and to highlight it.:

```css
:target {
    animation-name: highlight;
    animation-duration: 2s;
}
.admin-bar :target {
    scroll-margin-top: 1.5em;
}

@keyframes highlight {
    0% {background-color: rgba(255,255,0,0);}
    50% {background-color: rgba(255,255,0,.5);}
    100% {background-color: rgba(255,255,0,0);}
}
```

![Image](https://github.com/user-attachments/assets/43325ad9-be28-40e0-b2c5-a598bda25e88)

It's based on @indigoxela's code above and this article: https://snook.ca/archives/html_and_css/yellow-fade-technique-css-animations

**Comment by olafgrabienski** [comment]
@NormPlum Thanks for the CSS code! The approach looks interesting, and it generally works for me. I wanted to test the CSS on the Permissions page as well, but it seems that anchor links don't work anymore on that page. (I guess because of the filter at the top of the page, will have a closer look and report back.)

**Comment by olafgrabienski** [comment]
For reference, there are two older issue reports similar to this one.

- https://github.com/backdrop/backdrop-issues/issues/2068
- https://github.com/backdrop/backdrop-issues/issues/3414

The older issues are specifically about the Permissions page. This one has a more general focus, but let's keep the other issues in mind.

**Comment by olafgrabienski** [comment]
> I wanted to test the CSS on the Permissions page as well, but it seems that anchor links don't work anymore on that page. (I guess because of the filter at the top of the page, will have a closer look and report back.)

I've added an issue report re the Permissions page: https://github.com/backdrop/backdrop-issues/issues/7004

**Comment by NormPlum** [comment]
Here's updated CSS that should take sticky table headers into account (once the Permissions page bug is fixed):

```css
:target {
    animation-name: highlight;
    animation-duration: 2s;
}
.admin-bar :target {
    scroll-margin-top: 1.5em;
}
table.sticky-enabled :target {
    scroll-margin-top: 3em;
}
.admin-bar table.sticky-enabled :target {
    scroll-margin-top: 5em;
}

@keyframes highlight {
    0% {background-color: rgba(255,255,0,0);}
    50% {background-color: rgba(255,255,0,.5);}
    100% {background-color: rgba(255,255,0,0);}
}
```

**Comment by indigoxela** [comment]
Caution, the admin bar has a setting for "stickyness" on admin/config/administration/admin-bar, so the `scroll-margin-top` should only apply if the bar is set to sticky. That's `.admin-bar-sticky` 😉

**Comment by NormPlum** [comment]
I was looking for a class like that, but I couldn't find anything. Where is it defined/set?

**Comment by indigoxela** [comment]
> I was looking for a class like that, but I couldn't find anything. Where is it defined/set?

Oops, sorry, that was misleading... It came from my custom/contrib theme.
Actually, the admin-bar module doesn't set the class on the html item, but only sets `admin-bar-position-fixed` on the bar itself, where it's not very helpful.
That class is set in Backdrop.adminBar.behaviors.positionFixed in admin_bar.js.

Hopefully we find a way to add that info without introducing a breaking change for existing themes... CSS changes in core tend to be a bit tricky.

**Comment by NormPlum** [comment]
I opened an issue for the new class: https://github.com/backdrop/backdrop-issues/issues/7005

**Comment by olafgrabienski** [comment]
On a site with the new class and the fix for the Permissions page, I wanted to test the CSS on the Permissions page again. When I adapt the CSS from above to use the new class `.admin-bar-fixed` instead of `.admin-bar`, the target is still covered by the table header. I guess I'm just missing something.

**Comment by NormPlum** [comment]
Here's updated code based on @quicksketch's suggestion in the other ticket where I wanted to add a new class. We don't need it though, this code works instead:

```css
:target {
    animation-name: highlight;
    animation-duration: 2s;
}
html:has(.admin-bar-position-fixed) :target {
    scroll-margin-top: 1.5em;
}
table.sticky-enabled :target {
    scroll-margin-top: 3em;
}
html:has(.admin-bar-position-fixed) table.sticky-enabled :target {
    scroll-margin-top: 5.5em;
}

@keyframes highlight {
    0% {background-color: rgba(255,255,0,0);}
    50% {background-color: rgba(255,255,0,.5);}
    100% {background-color: rgba(255,255,0,0);}
}
```

However there's an issue with the Permissions page where the initial load covers the target, but if you re-submit the URL (focus the URL bar and hit Enter), it shows the target properly. So this is probably what @olafgrabienski was experiencing and seems to be a bug with that page.
