### ISSUE TITLE
Upload Simpletest Results as an Artifact in GHA

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6458]
## Description of the need

Debugging test failures in GitHub Actions is often difficult, because you can't see what is happening like you can when running tests locally through the UI. In particular, the contents of HTML pages that are loaded (and verbose messages) are helpful in that it shows you what the HTML browser sees while executing the test.

## Proposed solution

We could make things more transparent as to what's happening in our GitHub Action test runs by uploading the verbose output as an artifact and attaching it to the test runs.

## Alternatives that have been considered

I usually run tests locally when there is a failure, but occasionally there is an error that happens _only_ on GitHub (like we've been experiencing with #2277).

## Additional information

This can be achieved by adding this to the bottom of our test YML files:

```
      - name: Save Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: simpletest-output
          path: files/simpletest
```
