### ISSUE TITLE
[DX] Seven theme: Move CSS styles related to jQuery UI from style.css with the rest of them in jquery.ui.theme.css

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6544]
`core/themes/seven/css/style.css`:
```css
/* Dialogs */
.ui-dialog .ui-dialog-titlebar {
  background: #e9e8e8;
  font-size: 1.2em;
  font-weight: normal;
}
.ui-dialog .ui-dialog-buttonpane {
  background: #e9e8e8;
}
.ui-dialog {
  position: absolute;
  border: 1px solid #d0d0d0;
  border-radius: 4px;
  box-shadow: 0 0 12px -8px #666;
}
.ui-dialog-titlebar {
  border: 1px solid #d0d0d0;
  border-bottom: none;
  border-radius: 4px 4px 0 0;
}
```

`core/themes/seven/css/jquery.ui.theme.css`:
```css
/**
 * Dialogs
 */
.ui-dialog {
  background: #fff;
  border: solid 1px #ccc;
  padding: 0;
  z-index: 1001;
}
.ui-dialog .ui-dialog-titlebar {
  font-weight: bold;
  background: #f3f4ee;
}
.ui-dialog .ui-dialog-buttonpane {
  border-width: 0;
}
.ui-widget-overlay {
  background: #000;
  opacity: 0.2;
  filter: Alpha(opacity=20);
  z-index: 1000;
}
.ui-widget-shadow {
  box-shadow: 0 0 12px -8px #666;
}
```
