### ISSUE TITLE
Recipes: Allow installation of modules without making them "hard" dependencies

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6616]
It's been a while that this has been on my mind, and I believe that it will help with #5240 and #6595.

So in Drupal, the .info.yml files for distributions allow for both a hard `dependencies` declaration, as well as "soft dependencies" via a separate `install` declaration. For example, see the following from the [govcms.info.yml v3.x](https://github.com/govCMS/GovCMS/blob/3.x-develop/govcms.info.yml):
```yml
install:
  - drupal:big_pipe
  - drupal:block
  - drupal:block_content
  - drupal:ckeditor5
  - drupal:config
...
  - config_ignore:config_ignore
  - media_file_delete:media_file_delete
  - pathauto:pathauto

dependencies:
  - govcms_security
```

In the above example, only the govcms_security module is mandatory and cannot be uninstalled post-installation.

Further details about the various properties that can be added in .info.yml files of distributions/profiles can be found here: https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/creating-distributions/how-to-write-a-drupal-installation-profile. This is an excerpt that is relevant to this request here:
```yml
# Modules to install to support the profile.
# Unlike dependencies, these can be uninstalled later.
install:
  - ...

# Required modules. These cannot be uninstalled.
# Note that any dependencies of the modules listed here will be installed automatically.
dependencies:
  - node
  - block
  - views
```

So I think that we should also support a new `install` property for recipes.
