### ISSUE TITLE
Safari select elements not styled properly in Seven

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#995]
Followup from https://github.com/backdrop/backdrop-issues/issues/942.

In both desktop and mobile Safari, select elements are not styled properly.

This screenshot shows how the content search form appears in Safari:
![before-safari](https://cloud.githubusercontent.com/assets/100206/8120855/66dadc48-1061-11e5-9526-1a7309248c53.png)

But this is what it looks like in Firefox (correct):
![after](https://cloud.githubusercontent.com/assets/100206/8120866/73f6543e-1061-11e5-90e7-2ef94e817175.png)

**Comment by wesruv** [comment]
Also going to see if I can clear up some other Form styling inconsistencies across other browsers.

**Comment by tarekdj** [comment]
@quicksketch , @wesruv this is a litte hack that works for chrome, safari and FF on Windows 7. Needs tests on Mac OS before working on PR.
/core/themes/seven/css/style.css
```css
/* Safari hacks
   @todo: add RTL support */
html[xmlns*=""]:root select, :root select {
  padding-right: 25px;
  background: url('../../../misc/arrow-down.png') center right no-repeat;
  -webkit-appearance:none;
}
``` 
/core/misc/arrow-down.png attached.
![arrow-down](https://cloud.githubusercontent.com/assets/540268/10307905/e02987b8-6c21-11e5-8c12-8b8d2383e610.png)
